apiVersion: v1
kind: Service
metadata:
  name: wsn-api-service
  namespace: wsn-mlops
spec:
  selector:
    app: wsn-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
