apiVersion: v1
kind: Service
metadata:
  name: wsn-streamlit-service
  namespace: wsn-mlops
spec:
  selector:
    app: wsn-streamlit
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
  type: LoadBalancer
